pipeline {
  agent any

  stages {
    stage('Clone Repository') {
      steps {
        git url: 'https://github.com/kakadeabhi3000-rgb/python-project1', branch: 'main'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t python-project .'
      }
    }

    stage('Run Container') {
      steps {
        sh 'docker stop flask-container || true'
        sh 'docker rm flask-container || true'
        sh 'docker run -d --name flask-container -p 5000:5000 python-project'
      }
